version: ~> 1.0
sudo: false
language: node_js
node_js:
  - '10'
  - '12'
  - '13'
  - '14'
matrix:
  fast_finish: true
  allow_failures: []
cache: npm
install:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-install.bash)"
before_script:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-verify.bash)"
after_success:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-publish.bash)"
notifications:
  email:
    recipients: >-
      ltkKMOPLidZwKi2lvq/Ge7Owih5RP30vUAWtX1+dS15jyY1iyAWUq+hDbUslaazvPYLf7CH0oqpsOREDzQBtx4Fs7ppyLhZh4caSy83R40qaYQB384osiRj56qUyWe01RKHfSff9CEvQc+kZkbZb3Zv3M5+37obi1//6P18xjqMMQejmLBbTGMMu2MG3f+jfmQHhp22zp5VzP1eQm7vYqkxqQ7OsNo6tM0ViaK5DfHIrUe9H+b68zbY80fJrojEiihrgN2FNLdVHqJc+7KcDtK/V9Z6x7bpTIi78S8CTBUgARpVWlOpPIbxGVpeWHVgA3u9pkhkgZb59l+6OeRdU/uA7P/+AbQfGdWiKtDy1I0190UmoqWlRTX6y96q6lt8dN/3hXtXxW8NBwp2lNZXceHQxeg3BTk0S2+2kaq/Am8C0sf1pxLzjljFfLij86/nwVhqoXSUt+5ZzwkeMegf6I9i9f2/S3rxYelkfG+Y7S+w4JfnFDNQ9eEnN3QOmRB7MNGPvg53dMDU43wdUTKHj2WbzNM9fjpCm0g+H4tLBVbw2ySfA3JX+AvgR/clIrjYdjbnkkS7YQCs+YcBFvvghUhshDY/F4/uySNeGxb7u78wiovd1LEKXHxyzzgOQo9MC2KYLhqmFDoG3GcIdArTCteZA/e89xtREjeuugmICXzY=
