version: ~> 1.0
sudo: false
language: node_js
node_js:
  - '10'
  - '12'
  - '13'
  - '14'
matrix:
  fast_finish: true
  allow_failures: []
cache: npm
install:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-install.bash)"
before_script:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-verify.bash)"
after_success:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-publish.bash)"
notifications:
  email:
    recipients: >-
      VNAom+uRmungcNHoC4d1QROFjGbx3Pbdkd2V1l6RXAtS5hBHJkKp4PxxBpag+z1uY2u5Ge7EONnfroAv+ZFHz4zdMUagya+z5UoeALTXAenD654Z+TPV1WsytBRzGxxncKgwLHrkiwpncN5gstn1fu7TeQAfzScbvVDWD7c48STVCHy3ML1DrnoG19yt3IJeH0Xcn57kXZELLL6L/Z+NICg2qbYscSN9RqDO1SjuLkJeguSWoErpbJ0JCw5qTKbnuER7NBCPJGt1r5AZdjkgsW+zoejBnzTctGl0zsa6/z/XKrmO85ZhQCZNeOkFrugLIwwpn/NXRU3wjoPktRQKck2UHGfSR4Yw6Ny5P75W6g2xCFnYih/KhoDzlWy6ntlLOdiwyXZUVdlcXDhDYuIu7DBz1T7ED/rTn2VS2QIszlmQr86rCR3mo+pve1XNJ7NBycqVccL3riDGXbuJAEcKs9JWZhzGr+CaqCmtjD3hHS/tL4UwMMVSrC+M5d3he5HmkubTPELXgS/KyOhYOqme9XVLFckrZI8Akpd5z9bCVqNay2YQU4NEyAb0h6SazADrbrB0BSIsKdjpPiPbfhsN0CUmbw29mr0cpuhrqAFbdI+vvbRnsuWCY7z5ox38NyUeOWa+SvDMaUGf8MVzqfBbzWyBkdzx97hrzO8kfgTyydU=
