version: ~> 1.0
sudo: false
language: node_js
node_js:
  - '10'
  - '12'
  - '13'
  - '14'
matrix:
  fast_finish: true
  allow_failures: []
cache: npm
install:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-install.bash)"
before_script:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-verify.bash)"
after_success:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-publish.bash)"
notifications:
  email:
    recipients: >-
      LuYOwoNbio1OuFQROqBxdVQ/4HAtU5g5fbZkzqKLu7A4W6mA6fuiJkYPQo66QKDQ3rxNTXs8BttqfdvExYz0qDfVTVZuEWLmowY/vsNJDB7g9pnXj/sOTeRZh03IlXDscaC9qoDVzdvIQShdT1b+/6fkL8K146f2vUqT629QWRjt79p6FYHEhUr+Ec1tIt9PqZCtLX52udTG6pZ5V3RQfsZ8TE0CgP0nq4+xGXf5pyCgL9UppGUeqGDfNX+CX+jVTNygw0QZXwJA/hDYGwLIOXUsdcYMZjnKu76jZdjTA7A7sWQvd94areeZ8vxl0nl4qHu882RhWtd/ed6ith16X9qIBn65aUIJ6Go1PBRlwpDTwuUsbUyn6MGvF8JE+lvWMlD4EOoCipynwtBU8sSB/fSqYj+pEEDnkaC6gaf13ht/B69zaJgUl8i+oTwLmYKxTcCDBWVWtbQx/1Rw3R6NmkfbLAhz/TqhR3EeWgglcRb9yWO7UjbeQVUHiFEDpjdxVtYei0V+JePGGMX/G4hSy4tWq492C6Y+kf56/NEhXfnRzni7keP9lPryqoAn7rS4xqUESUEfzKTLo5Rt3e0RUafVWOL+4DizSkwhZZVdzgXhk4l29/8e2lgfRP0QaG2z93U87Z+Nc6sNcgHs0O5FuGpHED83wrHfi9tVwMp7bLw=
