sudo: false
language: node_js
node_js:
- '6'
- '8'
- '10'
- '12'
- '13'
matrix:
  fast_finish: true
  allow_failures: []
cache: npm
install:
- eval "$(curl -fsSL https://raw.githubusercontent.com/bevry/awesome-travis/c91c9d5eef34ecb0e92029667fd5052640225fa3/scripts/node-install.bash)"
before_script:
- eval "$(curl -fsSL https://raw.githubusercontent.com/bevry/awesome-travis/c91c9d5eef34ecb0e92029667fd5052640225fa3/scripts/node-verify.bash)"
after_success:
- eval "$(curl -fsSL https://raw.githubusercontent.com/bevry/awesome-travis/c91c9d5eef34ecb0e92029667fd5052640225fa3/scripts/node-publish.bash)"
notifications:
  email:
    recipients:
      secure: LuBdUV8yGrGJkJyE3irveU2666OAAQ33Lr7VmVH3KVNwb+V7F1JlPiua6zNtaTozJmuH6g8hJlGuVqfcdQlHRSz+l8WHyZI9gPGFhKKialvO6SFEuAK8DhDXCdult0hidsgXTuffwR04NeiwUnYZj9YkP3NPUJCcrCpgsmyy59RgALQt75Tv66ofbJ6/23IovL+EAqqAmJRg2DJmzXDzf0nUdrHOcJeC7y66PdAlrotqv5r9l8U5TZUjpHV91iEab3CAp+Dwg5XtQjxkuRWxDmxFxbwIeegZjHrw7Yh/HrPwjHCcjA2CeoGwHgzEELry54eQVMhly5Ylt+I7zJi3oTTGEVIosHblfDbRTP0Qyr1mpTGVRrOKXyzAmqaX9V/Hk1pOlhDuu5UmWcQSZ5U1QNje1TH0D0qBaCbVFhW7YER+xmtN2qmtGpD6n6uBsETKLaaudvyVLsM/9Oju5uvZ2Knc+ajsHcuSib0eTBMEiQZVu3+CsFCuCRq7rmGErMaSzEm4EP+DStFWNR0XYE1bX7aGyF3x1P1PtGpLdDLc4wC5zfoe3dASEtrFZmWXrq6Uk6EIuE+9Y4zx652ta/QzipaGppf+Bqy8jo23hZriKB/jJ2c03Tx+Ls93/lX9eErfoYqNs8Vaz1NqsF4WdS+WtIGAlvRR37PTH3AXQixhWPw=
