sudo: false
language: node_js
node_js:
- '6'
- '8'
- '10'
- '11'
matrix:
  fast_finish: true
  allow_failures: []
cache:
  directories:
  - "$HOME/.npm"
  - "$HOME/.yarn-cache"
install:
- eval "$(curl -fsSL https://raw.githubusercontent.com/bevry/awesome-travis/a16fffacc146944edb58d02bbc565bf467099b18/scripts/node-install.bash)"
before_script:
- eval "$(curl -fsSL https://raw.githubusercontent.com/bevry/awesome-travis/a16fffacc146944edb58d02bbc565bf467099b18/scripts/node-verify.bash)"
after_success:
- eval "$(curl -fsSL https://raw.githubusercontent.com/bevry/awesome-travis/a16fffacc146944edb58d02bbc565bf467099b18/scripts/node-publish.bash)"
notifications:
  email:
    recipients:
      secure: Oqz1DliJJlo1x+Acm1rARDY0L+9/lerxdVKkAh9n44Ab786UDQgSN7jDRxQTGvfyCnF9Ha7SZ87zijgXytnbzqYb0Tf2mNTGsZynlQU5hy0WhUJpldPfggeBuo1mEqurohVSnP7e49tPRWAgJrmVnHrla0mKuID8e5pbndobv131CQS0HGEcUUkCybt47RadI8Xj/zd6TGEMZhCl1khbBcX9tOmZVXLFnUCDu4pz8BPjNtiDB06NRjVcoLtQtxg7on6bvqBVloDFaou7c/8r88gxjbMcnCZ/I6BwkiPq6hKuP/bJuF3hemTd7wmIkL0Sblr5skI7Gjfje3vqwp9zZ1uUlA4vYSCP5bS7ybQimk2lM2LmKsDtM6O/9PJLukA4udZI6e6aSUMhunBdmQ3wDu4ymtYubI0/tAXyBbt+sZgE8aSEGobr5LYopE1Baxu4ixmPA6ONwjHJCvynkr6DcfzRpZXUbqzMx0yUQm0AM1YX/DgOVyb0CGgj/0w+4Z3W+/9bzlfF/d6yUcpxRO/RjFAD0rVZtYqmhX06J949IsjGzGFLbhrN/G7F5p/M4/makye1af6vxdoPo555wmoO29JBMHJ++28OuTgG73LUmqs49Tam0lhy4g4FJ+6/w2HRrYbS31glc7sz+J4gOHoAFrsAXDNish1MwQ42JnG3/P4=
